[project]
name = "r1-arc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "deepseek-tokenizer>=0.1.3",
    "devtools>=0.12.2",
    "numpy>=2.2.3",
    "openai>=1.66.1",
    "python-dotenv>=1.0.1",
    "tenacity>=9.0.0",
    "tiktoken>=0.9.0",
    "typer>=0.15.2",
]

[project.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "syrupy>=4.9.0",
]
