[project]
name = "r1-arc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.8.0",
    "asyncio>=3.4.3",
    "better-exceptions>=0.3.3",
    "deepseek-tokenizer>=0.1.3",
    "devtools>=0.12.2",
    "jinja2>=3.1.6",
    "logfire>=3.8.0",
    "numpy>=2.2.3",
    "openai>=1.66.1",
    "pygments>=2.19.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "python-dotenv>=1.0.1",
    "scipy>=1.15.2",
    "tenacity>=9.0.0",
    "tiktoken>=0.9.0",
    "typer>=0.15.2",
]

[project.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "syrupy>=4.9.0",
]

# Pytest only src/**/*
[tool.pytest.ini_options]
python_files = ["src/**/test_*.py"]
python_functions = ["test_*"]
